### ISSUE TITLE
The text window does not fill screen

### ISSUE THREAD

**Issue by SirLinares** [Elhary/obsidian-Pale#3]
Hello, this theme is superb, however when I open a page whether it is text or canvas it only fills half of the screen. How to fix this ?

![Capture d'écran 2024-09-13 142341](https://github.com/user-attachments/assets/0ceaf760-af2d-4684-8fc2-c1ebac62044a)

**Comment by hariiy-sys** [comment]
Hello, thank you for the feedback! The issue with the page only filling half of the screen has been fixed. Please check for the latest update and let me know if everything works fine now.

**Comment by SirLinares** [comment]
Thanks for the quick response! It's better but for me it still doesn't reach the bottom of the page
![image](https://github.com/user-attachments/assets/f9bd7d48-d97d-4126-a312-a66dae399309)

**Comment by hariiy-sys** [comment]
follow these steps to edit the theme:

1. **Locate the Theme File**: Go to the theme folder in your Obsidian vault. The path should be something like:  
   `C:\Users\Your Username\.obsidian\themes\Pale - 淡\theme.css`

2. **Open the File**: Use a text editor such as Notepad or Visual Studio Code to open the `theme.css` file.

3. **Find the Code Section**: Look for this section in the file (you can use `Ctrl + F` to search for `.mod-root .workspace-leaf`):
   ```css
   .mod-root .workspace-leaf {
       border-radius: 15px;
       padding: 15px;
       box-shadow: var(--shadow);
       margin: 10px;
       max-height: 1100px;
       height: auto;
   }
   ```

4. **Adjust the `max-height`**: Change `max-height: 1100px;` to match your screen resolution. For instance, if your screen height is 1440px, update it to `max-height: 1440px;`. Adjust as needed to fit your display.

5. **Save the File**: After making the change, save the file and check Obsidian to see the changes.

Feel free to customize other aspects of the theme's styling. Let me know if this solves the issue!
